pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world!' 
                echo 'Triggering jenkins pipeline 2'
            }
        }
    }
}
